import { AirdropOpportunity } from "./types";
import { computeAlphaScore } from "./scoring";

/**
 * MVP dataset — manually curated, ~15 entries. Quality over quantity.
 *
 * All reward / cost / time figures are analytical ESTIMATES for research
 * prioritization, not confirmed payouts. Funding and program details are
 * based on public reporting as of mid-2026 and may be out of date — always
 * marked `unverified` where the underlying token/allocation is not confirmed.
 */
const raw: Omit<AirdropOpportunity, "alphaScore">[] = [
  {
    id: "megaeth",
    name: "MegaETH",
    slug: "megaeth",
    chain: "Ethereum L2",
    category: "Infrastructure",
    status: "potential",
    scoreBreakdown: { tokenProbability: 16, expectedReward: 21, capitalEfficiency: 11, timeEfficiency: 12, competition: 6, risk: 11 },
    estimatedReward: { min: 200, max: 1200, currency: "USD" },
    estimatedCost: { min: 20, max: 80, currency: "USD" },
    estimatedTimeMinutesPerWeek: 60,
    tokenProbability: "high",
    competition: "high",
    risk: "medium",
    funding: { amount: 107_000_000, currency: "USD", investors: ["Vitalik Buterin (reported backer)", "multiple crypto VCs"] },
    description: "High-throughput 'real-time' EVM rollup positioning itself as the fastest Ethereum L2. Large funding round and heavy testnet attention, no confirmed token yet.",
    whyWeLikeIt: [
      "Reported $107M raise gives it one of the largest war chests among pre-token L2s",
      "Testnet activity and developer attention have been consistently high",
      "No token announced yet, leaving upside if a community allocation follows the usual L2 playbook",
    ],
    risks: [
      "No confirmed token or allocation mechanics — this is a probability bet, not a confirmed reward",
      "High-profile status means testnet activity is heavily farmed, which can dilute per-wallet rewards",
      "Mainnet timeline and eligibility criteria have not been published",
    ],
    farmingSteps: [
      { title: "Set up a dedicated wallet", description: "Use a wallet with organic-looking history rather than a fresh burner.", estimatedTime: "10 min" },
      { title: "Bridge a modest amount", description: "Bridge a small, realistic amount to the testnet/mainnet as available.", estimatedCost: "$20-50", estimatedTime: "10 min" },
      { title: "Use core dApps weekly", description: "Interact with flagship apps on the network on a recurring basis rather than in one burst." },
      { title: "Track official channels", description: "Watch for any snapshot or eligibility announcement." },
    ],
    officialWebsite: "https://megaeth.com",
    lastUpdated: "2026-08-01",
    lastVerified: "2026-08-01",
    sourceType: "curated_research",
    tags: ["L2", "EVM", "high-funding"],
    unverified: true,
  },
  {
    id: "monad",
    name: "Monad",
    slug: "monad",
    chain: "Monad L1",
    category: "Infrastructure",
    status: "potential",
    scoreBreakdown: { tokenProbability: 16, expectedReward: 20, capitalEfficiency: 12, timeEfficiency: 12, competition: 6, risk: 11 },
    estimatedReward: { min: 150, max: 900, currency: "USD" },
    estimatedCost: { min: 10, max: 60, currency: "USD" },
    estimatedTimeMinutesPerWeek: 45,
    tokenProbability: "high",
    competition: "high",
    risk: "medium",
    funding: { amount: 244_000_000, currency: "USD", investors: ["multiple crypto VCs"] },
    description: "Parallelized EVM-compatible L1 aiming for very high throughput. One of the best-funded pre-token L1s in this cycle.",
    whyWeLikeIt: [
      "Reported funding above $240M signals a long runway and strong institutional interest",
      "Ecosystem incentive programs and app-layer testnets are already live",
      "Strong developer mindshare relative to other new L1s",
    ],
    risks: [
      "Very high visibility means intense competition from farming communities and bots",
      "No token or distribution mechanics confirmed",
      "New L1s carry execution risk even after a strong fundraise",
    ],
    farmingSteps: [
      { title: "Get testnet/ecosystem access", description: "Follow official onboarding for the current network phase." },
      { title: "Use 2-3 ecosystem apps regularly", description: "Prioritize apps with their own points programs layered on top." },
      { title: "Keep activity spread over weeks", description: "Consistent, spaced-out usage tends to outperform one-off bursts." },
    ],
    officialWebsite: "https://www.monad.xyz",
    lastUpdated: "2026-08-01",
    lastVerified: "2026-08-01",
    sourceType: "curated_research",
    tags: ["L1", "EVM", "high-funding"],
    unverified: true,
  },
  {
    id: "layerzero-zero",
    name: "LayerZero (Zero L1 expansion)",
    slug: "layerzero",
    chain: "Multi-chain",
    category: "Infrastructure",
    status: "active",
    scoreBreakdown: { tokenProbability: 10, expectedReward: 14, capitalEfficiency: 12, timeEfficiency: 12, competition: 7, risk: 11 },
    estimatedReward: { min: 50, max: 400, currency: "USD" },
    estimatedCost: { min: 5, max: 30, currency: "USD" },
    estimatedTimeMinutesPerWeek: 20,
    tokenProbability: "medium",
    competition: "medium",
    risk: "medium",
    funding: { amount: undefined, investors: ["Tether (reported strategic investment)"] },
    description: "Established cross-chain messaging protocol (ZRO token already live) that announced its own L1, Zero, in February 2026 with strategic backing reported from Tether. Team has stated ZRO keeps a role in upcoming initiatives rather than a new token launching.",
    whyWeLikeIt: [
      "Already has a large future community allocation from the existing ZRO tokenomics",
      "New Zero L1 expands the ecosystem and creates fresh, lower-competition surface area",
      "Reported strategic backing (Tether) adds credibility to continued ecosystem investment",
    ],
    risks: [
      "Team has indicated no new token is planned — upside here is about ZRO's expanding role, not a fresh airdrop",
      "Cross-chain history matters more than one-off activity, which rewards patience over quick farming",
      "Mechanics for any future community allocation from Zero are not published",
    ],
    farmingSteps: [
      { title: "Build genuine cross-chain history", description: "Use LayerZero-powered bridges/apps as part of normal activity, not in isolation." },
      { title: "Follow Zero L1 rollout", description: "Track official announcements for any Zero-specific programs." },
    ],
    officialWebsite: "https://layerzero.network",
    lastUpdated: "2026-08-10",
    lastVerified: "2026-08-10",
    sourceType: "live_defillama",
    tags: ["messaging", "cross-chain", "established"],
    unverified: true,
  },
  {
    id: "base-network-token",
    name: "Base (network-level token speculation)",
    slug: "base",
    chain: "Base",
    category: "L2",
    status: "potential",
    scoreBreakdown: { tokenProbability: 9, expectedReward: 15, capitalEfficiency: 13, timeEfficiency: 13, competition: 5, risk: 10 },
    estimatedReward: { min: 50, max: 500, currency: "USD" },
    estimatedCost: { min: 5, max: 40, currency: "USD" },
    estimatedTimeMinutesPerWeek: 30,
    tokenProbability: "medium",
    competition: "high",
    risk: "medium",
    description: "Coinbase's L2 has been publicly reported to be exploring a network-level token, without a confirmed launch date or mechanics.",
    whyWeLikeIt: [
      "Massive existing user base and app ecosystem gives a wide, organic activity surface",
      "Public exploration of a token (per reporting) is itself a signal, even without confirmation",
      "Many sub-ecosystems (perps, social, gaming apps) run their own points programs on top of Base activity",
    ],
    risks: [
      "No confirmed token, timeline, or eligibility criteria from the Base team",
      "Coinbase's regulatory posture could shape (or delay) any token decision",
      "High user volume means any eventual allocation may be spread thin per wallet",
    ],
    farmingSteps: [
      { title: "Use flagship Base apps", description: "Maintain regular activity across a few well-known Base-native apps." },
      { title: "Layer app-specific points programs", description: "Many apps on Base run their own campaigns worth farming independently." },
    ],
    officialWebsite: "https://base.org",
    lastUpdated: "2026-08-05",
    lastVerified: "2026-08-05",
    sourceType: "curated_research",
    tags: ["L2", "Coinbase", "speculative"],
    unverified: true,
  },
  {
    id: "polymarket-points",
    name: "Polymarket",
    slug: "polymarket",
    chain: "Polygon",
    category: "Prediction markets",
    status: "upcoming",
    scoreBreakdown: { tokenProbability: 18, expectedReward: 17, capitalEfficiency: 10, timeEfficiency: 10, competition: 6, risk: 12 },
    estimatedReward: { min: 80, max: 600, currency: "USD" },
    estimatedCost: { min: 20, max: 200, currency: "USD" },
    estimatedTimeMinutesPerWeek: 40,
    tokenProbability: "high",
    competition: "medium",
    risk: "medium",
    description: "Leading prediction market platform with a publicly confirmed token and airdrop direction, though exact distribution mechanics have not been published.",
    whyWeLikeIt: [
      "Token and airdrop direction are publicly confirmed by the team — rare in this cycle",
      "Rewards engagement across diverse market categories, not just raw volume",
      "Real product-market fit reduces the 'farm for a dead project' risk",
    ],
    risks: [
      "Distribution mechanics and snapshot timing are still unpublished",
      "Trading real markets means real capital is at risk beyond pure gas/fees",
      "Confirmed token does not guarantee retail-friendly allocation size",
    ],
    farmingSteps: [
      { title: "Fund an account with modest capital", description: "Start with an amount you're fully comfortable risking on outcomes.", estimatedCost: "$20-200" },
      { title: "Trade across diverse categories", description: "Diversify across market types rather than concentrating in one." },
      { title: "Track official distribution updates", description: "Watch for published mechanics once announced." },
    ],
    officialWebsite: "https://polymarket.com",
    lastUpdated: "2026-08-12",
    lastVerified: "2026-08-12",
    sourceType: "live_defillama",
    tags: ["prediction-markets", "confirmed-token"],
    unverified: true,
  },
  {
    id: "backpack-exchange",
    name: "Backpack Exchange",
    slug: "backpack-exchange",
    chain: "Solana",
    category: "Exchange / Perpetuals",
    status: "active",
    scoreBreakdown: { tokenProbability: 19, expectedReward: 16, capitalEfficiency: 9, timeEfficiency: 11, competition: 7, risk: 12 },
    estimatedReward: { min: 60, max: 500, currency: "USD" },
    estimatedCost: { min: 10, max: 150, currency: "USD" },
    estimatedTimeMinutesPerWeek: 45,
    tokenProbability: "high",
    competition: "medium",
    risk: "medium",
    description: "Solana-based exchange with a publicly posted TGE plan (Feb 2026): 25% of token supply to the community, split between points holders and Mad Lads NFT holders, running its fourth points season.",
    whyWeLikeIt: [
      "Team has publicly posted a TGE plan with a specific community allocation percentage",
      "Points are calculated weekly on a transparent, published cadence",
      "Rewards consistent trading activity over one-off volume spikes",
    ],
    risks: [
      "Real trading fees and market exposure apply, not just gas costs",
      "Final points-to-token conversion ratio is not yet published",
      "Mad Lads NFT path adds an extra cost layer some farmers won't want to take on",
    ],
    farmingSteps: [
      { title: "Open an account and fund lightly", description: "Start with a small balance for spot and low-leverage perp trading.", estimatedCost: "$10-150" },
      { title: "Trade weekly before the Friday points cutoff", description: "Points are calculated weekly, so consistency compounds." },
      { title: "Consider a Mad Lads NFT if budget allows", description: "Grants VIP status and a separate allocation, at extra cost.", estimatedCost: "varies" },
    ],
    officialWebsite: "https://backpack.exchange",
    lastUpdated: "2026-08-01",
    lastVerified: "2026-08-01",
    sourceType: "curated_research",
    tags: ["exchange", "points-program", "published-plan"],
    unverified: true,
  },
  {
    id: "metamask-rewards",
    name: "MetaMask Rewards",
    slug: "metamask",
    chain: "Multi-chain",
    category: "Wallet",
    status: "upcoming",
    scoreBreakdown: { tokenProbability: 17, expectedReward: 15, capitalEfficiency: 14, timeEfficiency: 13, competition: 5, risk: 12 },
    estimatedReward: { min: 40, max: 350, currency: "USD" },
    estimatedCost: { min: 0, max: 30, currency: "USD" },
    estimatedTimeMinutesPerWeek: 20,
    tokenProbability: "high",
    competition: "medium",
    risk: "low",
    description: "Consensys has publicly stated a MASK token is coming, alongside a seasonal, level-based MetaMask Rewards points system tied to swaps, perps and bridging inside the wallet app.",
    whyWeLikeIt: [
      "Consensys leadership has publicly confirmed a token is coming",
      "Very low capital requirement since it rewards normal wallet usage",
      "Enormous existing user base with a straightforward, low-effort activity path",
    ],
    risks: [
      "Exact points mechanics for MetaMask Rewards are not fully detailed yet",
      "Huge eligible user base could mean small per-wallet allocations",
      "No confirmed snapshot date",
    ],
    farmingSteps: [
      { title: "Use MetaMask's built-in swap and bridge features", description: "Route routine swaps/bridges through the wallet's native features rather than external apps." },
      { title: "Try MetaMask perps if comfortable", description: "Perps trading inside the app is highlighted as a reward-relevant activity.", estimatedCost: "varies" },
    ],
    officialWebsite: "https://metamask.io",
    lastUpdated: "2026-08-01",
    lastVerified: "2026-08-01",
    sourceType: "curated_research",
    tags: ["wallet", "low-effort", "confirmed-token"],
    unverified: true,
  },
  {
    id: "fogo-flames",
    name: "Fogo",
    slug: "fogo",
    chain: "Fogo (SVM)",
    category: "Infrastructure",
    status: "active",
    scoreBreakdown: { tokenProbability: 16, expectedReward: 13, capitalEfficiency: 13, timeEfficiency: 13, competition: 8, risk: 10 },
    estimatedReward: { min: 30, max: 250, currency: "USD" },
    estimatedCost: { min: 0, max: 20, currency: "USD" },
    estimatedTimeMinutesPerWeek: 20,
    tokenProbability: "high",
    competition: "medium",
    risk: "medium",
    description: "Solana-VM-compatible L1 targeting very low latency, which canceled a planned $20M presale in favor of airdropping the equivalent token allocation to its Fogo Flames points program and bridge users.",
    whyWeLikeIt: [
      "Team explicitly redirected presale allocation into a community airdrop instead",
      "Published tokenomics with a stated community share",
      "Low capital requirement — mostly testnet and bridge participation",
    ],
    risks: [
      "New, unproven L1 with execution risk",
      "Snapshot already covers past activity, so new entrants may have limited upside",
      "Broader points-to-reward conversion for new activity isn't guaranteed",
    ],
    farmingSteps: [
      { title: "Bridge via Portal Bridge", description: "Use the officially referenced bridge for eligible activity.", estimatedCost: "$0-20" },
      { title: "Stay active as 'Fogo Fishers'", description: "Participate in the ongoing points/testnet activity the team has referenced." },
    ],
    officialWebsite: "https://fogo.io",
    lastUpdated: "2026-08-01",
    lastVerified: "2026-08-01",
    sourceType: "curated_research",
    tags: ["L1", "SVM", "published-plan"],
    unverified: true,
  },
  {
    id: "grvt-rewards",
    name: "GRVT",
    slug: "grvt",
    chain: "zkSync-based",
    category: "Perpetuals",
    status: "active",
    scoreBreakdown: { tokenProbability: 14, expectedReward: 12, capitalEfficiency: 11, timeEfficiency: 12, competition: 8, risk: 9 },
    estimatedReward: { min: 30, max: 200, currency: "USD" },
    estimatedCost: { min: 10, max: 100, currency: "USD" },
    estimatedTimeMinutesPerWeek: 30,
    tokenProbability: "medium",
    competition: "medium",
    risk: "medium",
    funding: { amount: 5_000_000, currency: "USD", investors: ["Further Ventures"] },
    description: "Hybrid CEX/DEX perpetuals exchange running a points-based rewards program (Rewards 2.0), with a stated Q1 2026 TGE target and 20% of supply earmarked for community rewards.",
    whyWeLikeIt: [
      "Team has published a specific community rewards percentage",
      "Single points system with a transparent weekly leaderboard mechanic",
      "Smaller, less crowded platform relative to top-tier perps exchanges",
    ],
    risks: [
      "TGE timing has already slipped relative to earlier guidance in similar programs — treat dates as directional",
      "Perpetuals trading carries real market and liquidation risk",
      "Smaller user base means less external scrutiny of eventual distribution fairness",
    ],
    farmingSteps: [
      { title: "Trade with modest, low-leverage positions", description: "Points accrue from trading, holding positions and referrals.", estimatedCost: "$10-100" },
      { title: "Avoid unnecessary liquidations", description: "The program has noted liquidation-related point effects; trade conservatively." },
    ],
    officialWebsite: "https://grvt.io",
    lastUpdated: "2026-08-01",
    lastVerified: "2026-08-01",
    sourceType: "live_defillama",
    tags: ["perpetuals", "points-program"],
    unverified: true,
  },
  {
    id: "succinct-prover",
    name: "Succinct",
    slug: "succinct",
    chain: "Multi-chain (ZK infra)",
    category: "Infrastructure",
    status: "potential",
    scoreBreakdown: { tokenProbability: 13, expectedReward: 14, capitalEfficiency: 14, timeEfficiency: 13, competition: 9, risk: 10 },
    estimatedReward: { min: 40, max: 300, currency: "USD" },
    estimatedCost: { min: 0, max: 15, currency: "USD" },
    estimatedTimeMinutesPerWeek: 25,
    tokenProbability: "medium",
    competition: "low",
    risk: "medium",
    description: "Zero-knowledge proving network (SP1 prover) with an active testnet/prover points program and no confirmed token as of this writing.",
    whyWeLikeIt: [
      "Zero-knowledge infrastructure is a well-precedented airdrop category (see Scroll, Starknet, zkSync)",
      "Lower general-audience awareness than flagship L1s/L2s means comparatively lower competition",
      "Very low capital requirement — mostly compute/testnet participation",
    ],
    risks: [
      "No confirmed token or allocation mechanics",
      "More technical entry barrier (running a prover node) than simple wallet farms",
      "ZK infra category has already seen several TGEs, so timing/appetite for another is uncertain",
    ],
    farmingSteps: [
      { title: "Join the testnet/prover network", description: "Follow official docs to run a node or delegate to one, depending on program design." },
      { title: "Stay active across program phases", description: "Historically, sustained multi-phase participation has outperformed one-off signups." },
    ],
    officialWebsite: "https://succinct.xyz",
    lastUpdated: "2026-08-01",
    lastVerified: "2026-08-01",
    sourceType: "curated_research",
    tags: ["zk", "infrastructure", "low-competition"],
    unverified: true,
  },
  {
    id: "eclipse-svm",
    name: "Eclipse",
    slug: "eclipse",
    chain: "Ethereum (SVM execution)",
    category: "L2",
    status: "potential",
    scoreBreakdown: { tokenProbability: 12, expectedReward: 13, capitalEfficiency: 12, timeEfficiency: 12, competition: 8, risk: 10 },
    estimatedReward: { min: 30, max: 250, currency: "USD" },
    estimatedCost: { min: 5, max: 30, currency: "USD" },
    estimatedTimeMinutesPerWeek: 25,
    tokenProbability: "medium",
    competition: "medium",
    risk: "medium",
    description: "Ethereum L2 using the SVM for execution, combining Solana-style throughput with Ethereum settlement. No confirmed token as of this writing.",
    whyWeLikeIt: [
      "Distinctive technical positioning (SVM execution on Ethereum) gives it a differentiated ecosystem to farm",
      "Growing set of native apps building specifically for the SVM-on-Ethereum niche",
      "Moderate rather than saturated attention compared to top-tier L2s",
    ],
    risks: [
      "No confirmed token or snapshot criteria",
      "Ecosystem is younger and thinner than major L2s, so app-level activity options are more limited",
      "SVM-on-Ethereum is a less proven combination than either chain alone",
    ],
    farmingSteps: [
      { title: "Bridge a small amount", description: "Use the official bridge to move a modest balance in.", estimatedCost: "$5-30" },
      { title: "Use native SVM apps on the network", description: "Interact with the ecosystem's flagship DeFi/app-layer projects." },
    ],
    officialWebsite: "https://www.eclipse.xyz",
    lastUpdated: "2026-08-01",
    lastVerified: "2026-08-01",
    sourceType: "curated_research",
    tags: ["L2", "SVM", "niche"],
    unverified: true,
  },
  {
    id: "hyperliquid-ecosystem-apps",
    name: "HyperEVM ecosystem apps",
    slug: "hyperevm-apps",
    chain: "HyperEVM",
    category: "DeFi",
    status: "active",
    scoreBreakdown: { tokenProbability: 12, expectedReward: 15, capitalEfficiency: 11, timeEfficiency: 11, competition: 7, risk: 9 },
    estimatedReward: { min: 40, max: 300, currency: "USD" },
    estimatedCost: { min: 10, max: 60, currency: "USD" },
    estimatedTimeMinutesPerWeek: 40,
    tokenProbability: "medium",
    competition: "medium",
    risk: "medium",
    description: "A basket-style entry covering pre-token DeFi apps building on HyperEVM (Hyperliquid's EVM layer). Individual apps run their own points programs; none have confirmed tokens as of this writing.",
    whyWeLikeIt: [
      "Builds on Hyperliquid's strong existing user base and on-chain activity",
      "Several apps run overlapping points programs, creating 'double-dip' potential from the same underlying activity",
      "Category has a strong precedent given Hyperliquid's own 2024 distribution",
    ],
    risks: [
      "This entry bundles multiple apps of varying maturity and legitimacy — do your own diligence per app",
      "No individual app here has a confirmed token",
      "Precedent from Hyperliquid's own airdrop does not guarantee similar outcomes for apps built on top of it",
    ],
    farmingSteps: [
      { title: "Pick 2-3 established HyperEVM apps", description: "Favor apps with real usage and clear points documentation over brand-new, unaudited ones." },
      { title: "Spread modest capital across them", description: "Avoid concentrating capital in a single unproven app.", estimatedCost: "$10-60" },
    ],
    officialWebsite: "https://hyperliquid.xyz",
    lastUpdated: "2026-08-01",
    lastVerified: "2026-08-01",
    sourceType: "curated_research",
    tags: ["DeFi", "basket", "double-dip"],
    unverified: true,
  },
  {
    id: "checkpoint-points-marketplace",
    name: "Checkpoint",
    slug: "checkpoint",
    chain: "Multi-chain",
    category: "Social / Infrastructure",
    status: "potential",
    scoreBreakdown: { tokenProbability: 8, expectedReward: 9, capitalEfficiency: 15, timeEfficiency: 14, competition: 8, risk: 8 },
    estimatedReward: { min: 10, max: 100, currency: "USD" },
    estimatedCost: { min: 0, max: 5, currency: "USD" },
    estimatedTimeMinutesPerWeek: 15,
    tokenProbability: "low",
    competition: "medium",
    risk: "medium",
    description: "A points marketplace that gives testnet XP for use — a meta layer on top of other airdrop farming, with no confirmed token.",
    whyWeLikeIt: [
      "Near-zero capital requirement",
      "Interesting meta-narrative (a marketplace for points itself) with low time cost",
      "Can be layered on top of other farming activity rather than replacing it",
    ],
    risks: [
      "No confirmed token — this is a speculative, low-conviction entry",
      "Meta/points-marketplace narratives have a mixed track record of converting into real value",
      "Limited public information to verify team or mechanics claims",
    ],
    farmingSteps: [
      { title: "Sign up and complete basic onboarding", description: "Low time cost, treat as a side bet rather than a core focus." },
    ],
    officialWebsite: undefined,
    lastUpdated: "2026-08-01",
    lastVerified: "2026-08-01",
    sourceType: "curated_research",
    tags: ["low-conviction", "low-cost", "meta"],
    unverified: true,
  },
  {
    id: "truenorth-integrations",
    name: "TrueNorth",
    slug: "truenorth",
    chain: "Multi-chain",
    category: "Infrastructure",
    status: "potential",
    scoreBreakdown: { tokenProbability: 9, expectedReward: 11, capitalEfficiency: 14, timeEfficiency: 13, competition: 7, risk: 9 },
    estimatedReward: { min: 15, max: 120, currency: "USD" },
    estimatedCost: { min: 0, max: 10, currency: "USD" },
    estimatedTimeMinutesPerWeek: 15,
    tokenProbability: "low",
    competition: "medium",
    risk: "medium",
    description: "A project most useful for the 'double-dip' opportunities created by its integrations with other pre-token protocols, rather than as a standalone farm.",
    whyWeLikeIt: [
      "Low standalone cost and time — mainly valuable as an add-on to activity you're already doing",
      "Integration-driven design can multiply the value of effort spent elsewhere",
    ],
    risks: [
      "No confirmed token",
      "Value is contingent on the health of the projects it integrates with",
      "Weakest conviction entry in this dataset — treat as speculative upside, not a core allocation",
    ],
    farmingSteps: [
      { title: "Check which integrations apply to your existing activity", description: "Only worth dedicated time if it overlaps with farms you're already running." },
    ],
    officialWebsite: undefined,
    lastUpdated: "2026-08-01",
    lastVerified: "2026-08-01",
    sourceType: "curated_research",
    tags: ["low-conviction", "integration-based"],
    unverified: true,
  },
];

export const opportunities: AirdropOpportunity[] = raw.map((op) => ({
  ...op,
  alphaScore: computeAlphaScore(op.scoreBreakdown),
}));

export function getOpportunityBySlug(slug: string): AirdropOpportunity | undefined {
  return opportunities.find((o) => o.slug === slug);
}

export const CHAINS = Array.from(new Set(opportunities.map((o) => o.chain))).sort();
export const CATEGORIES = Array.from(new Set(opportunities.map((o) => o.category))).sort();
